inoremap jk <ESC>
let mapleader = "'"
syntax on
set number
set noswapfile
set hlsearch
set ignorecase
set incsearch
set nospell
set cursorline
nnoremap <leader>f 1z=
nnoremap <leader>s :set spell!
vnoremap . :norm.<CR>
highlight SpellBad cterm=underline ctermfg=red ctermbg=NONE
