# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="$HOME/.local/bin:/opt/homebrew/bin:$HOME/.composer/vendor/bin:$PATH"

# Path to your oh-my-zsh installation.
export ZSH="/Users/arunas/.oh-my-zsh"

export TERM="xterm-256color"
[[ -n $TMUX ]] && export TERM="screen-256color"

export COMPOSER_MEMORY_LIMIT=4G
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export SNAP_HAPPY_SCREENSHOT_PATH="/Users/arunas/Screenshots"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="robbyrussell"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration
ulimit -Sn 4096

if [[ `uname` == Darwin ]]; then
    MAX_MEMORY_UNITS=KB
else
    MAX_MEMORY_UNITS=MB
fi

TIMEFMT='%J   %U  user %S system %P cpu %*E total'$'\n'\
'avg shared (code):         %X KB'$'\n'\
'avg unshared (data/stack): %D KB'$'\n'\
'total (sum):               %K KB'$'\n'\
'max memory:                %M '$MAX_MEMORY_UNITS''$'\n'\
'page faults from disk:     %F'$'\n'\
'other page faults:         %R'

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias br="composer install && php artisan migrate && yarn install && yarn dev"
alias brw="composer install && php artisan migrate && yarn install && yarn watch"
alias brh="composer install && php artisan migrate && yarn install && yarn hot"
alias gb="git branch"
alias gs="git status"
alias gbm="git branch --merged main | grep -v '^[ *]*main$'"
alias gmaster="git checkout master && git pull origin master"
alias gitcommiturl="gh browse \$(git rev-parse HEAD) --no-browser"
alias tinker="php artisan tinker"
alias art="php artisan"
alias work="php artisan queue:work --queue=priority,default,sync-queue,export-processing-queue,long-scheduled-jobs,ledger --tries=2 --timeout=90"
alias killdns="sudo killall -HUP mDNSResponder"
alias localip='ifconfig | sed -n "s/^.*inet \(192.[0-9]*.[0-9]*.[0-9]*\).*$/\1/p"'
alias serve='php artisan serve --host=`localip`'
alias json='python -m json.tool < '
alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'
alias spostgres="brew services stop mysql@5.7 && brew services start postgresql@14"
alias smysql="brew services stop postgresql@14 && brew services start mysql@5.7"
alias spin='[ -f node_modules/.bin/spin ] && bash node_modules/.bin/spin || bash vendor/bin/spin'


function gpull () {
  if [ -z "$1" ]
    then
      git pull origin `git rev-parse --abbrev-ref HEAD`
    else
      git pull origin $1
  fi
}
function greb () {
  if [ -z "$1" ]
    then
      git pull --rebase origin `git rev-parse --abbrev-ref HEAD`
    else
      git pull --rebase origin $1
  fi
}
function gpush () {
  if [ -z "$1" ]
    then
      git push origin `git rev-parse --abbrev-ref HEAD`
    else
      git push origin $1
  fi
}
function gpushf () {
  if [ -z "$1" ]
    then
      git push origin `git rev-parse --abbrev-ref HEAD` --force
    else
      git push origin $1 --force
  fi
}
function ch() { git checkout $1; gpull; }
function gac() { git add . && git commit -m "$*" }
alias greset="git checkout -- . && git clean -fd"

alias mfs="php artisan migrate:fresh --seed"
alias mrs="php artisan migrate:refresh --seed"
alias mf="php artisan migrate:fresh"
alias vapor="vendor/bin/vapor"
alias tt="art test --parallel && npm test"
alias gself='f() { git log --since="$1 days ago" --author="$(git config user.name)" --pretty=format:"%C(yellow)%h%C(reset) %C(dim white)%ad%C(reset) %C(green)%d%C(reset) %s" --date=local; }; f'
alias cdr="cd \"\$(git rev-parse --show-toplevel)\""
alias n="nvim ."
alias vim="nvim"
alias lg="lazygit"
alias nconf="nvim ~/.config/nvim"
alias re-source="source ~/.zshrc"
alias gu="git pull origin main && git fetch"
alias squash="wt step squash"

source ~/.zshrcprivate

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion"


# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/arunas/.lmstudio/bin"

alias sleep-disable="sudo pmset -b disablesleep 1"
alias sleep-enable="sudo pmset -b disablesleep 0"
alias sleep-status="pmset -g | grep -q 'SleepDisabled.*1' && echo \"sleep disabled\" || echo \"sleep enabled\""
alias clearwork="php artisan queue:clear && php artisan queue:flush && work"
alias inspire="pi --provider anthropic --model claude-sonnet-4-6:low -p \"\$(date +%s): Give a random inspirational quote\""
alias update="claude update && npm install -g @mariozechner/pi-coding-agent backlog.md && inspire"
alias c="codex"
alias cc="claude"
alias b="npm run build && npm run marketing:build"
alias bo="npm install && npm run build && npm run marketing:build && valet open"
alias ssh-buhalterija="ssh ploi@49.13.112.18"

impl() {
  if [ "$#" -ne 1 ]; then
    printf 'usage: impl <arg>\n' >&2
    return 2
  fi

  local arg="$1"
  local rc

  if wt switch -c "$arg"; then
    :
  else
    rc=$?

    if git show-ref --verify --quiet "refs/heads/$arg"; then
      wt switch "$arg" || return
    else
      return "$rc"
    fi
  fi

  composer install
  npm install
  codex "\$wf-implement-review-loop $arg"
}

alias db='open -a TablePlus "$(git rev-parse --show-toplevel)/database/database.sqlite"'

function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	command yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ "$cwd" != "$PWD" ] && [ -d "$cwd" ] && builtin cd -- "$cwd"
	command rm -f -- "$tmp"
}

export PHPDOC_PLANTUML_BIN=/opt/homebrew/bin/plantuml

# bun completions
[ -s "/Users/arunas/.bun/_bun" ] && source "/Users/arunas/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# opencode
export PATH=/Users/arunas/.opencode/bin:$PATH

export BEADS_DIR=~/.beads/agenthub

if command -v wt >/dev/null 2>&1; then eval "$(command wt config shell init zsh)"; fi
export PATH="$(brew --prefix libpq)/bin:$PATH"
fpath=(/opt/homebrew/share/zsh/site-functions $fpath)
autoload -Uz compinit && compinit
